version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: student_fee_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: